# Generated by Django 4.1.5 on 2025-07-04 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_alter_equipmentgroup_options_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('equipment_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='equipment.equipmentitem')),
                ('price_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='equipment.equipmentpricerule')),
                ('rental_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='users.rentaluser')),
            ],
            options={
                'verbose_name': 'rental',
                'verbose_name_plural': 'rentals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_end_date', models.DateTimeField()),
                ('new_end_date', models.DateTimeField()),
                ('additional_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='rental.rental')),
            ],
            options={
                'verbose_name': 'rental extension',
                'verbose_name_plural': 'rental extensions',
                'ordering': ['-created_at'],
            },
        ),
    ]
