# Generated by Django 4.1.5 on 2025-07-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='price_rule',
        ),
    ]
