version: "3"

services:
  db:
    image: mariadb:10.11
    
    restart: unless-stopped
    ports:
      - "4316:3306"
    env_file:
      - .env
    volumes:
      - "mysql_data:/var/lib/mysql"

  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: varaamo_django
    command: pipenv run manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: varaamo.settings.development
      DB_HOST: db
    volumes:
      - .:/code
    depends_on:
      - db

  sveltekit:
    build:
      context: .
      dockerfile: ./varaamo-frontend/Dockerfile
    restart: always
    volumes:
      - ./varaamo-frontend:/app
      - node_modules:/app/node_modules

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8030:80"
    depends_on:
      - django
      - sveltekit
volumes:
  mysql_data: