[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.pylint.messages_control]
disable = ["C0114", "C0115", "C0116", "R0903"]  # missing-class-docstring, too-few-public-methods