# Generated by Django 4.1.5 on 2023-03-25 13:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EquipmentClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=10)),
                ("visible", models.BooleanField(default=True)),
                ("rentable", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "equipment class",
                "verbose_name_plural": "equipment classes",
            },
        ),
        migrations.CreateModel(
            name="EquipmentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(editable=False, max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="equipment_images/")),
            ],
        ),
        migrations.CreateModel(
            name="EquipmentPriceGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(editable=False, max_length=100)),
            ],
            options={
                "verbose_name": "equipment price group",
                "verbose_name_plural": "equipment price groups",
            },
        ),
        migrations.CreateModel(
            name="EquipmentPriceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "member_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("hour", "Hour"),
                            ("day", "Day"),
                            ("weekend", "Weekend"),
                            ("week", "Week"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "price_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="equipment.equipmentpricegroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "equipment price rule",
                "verbose_name_plural": "equipment price rules",
            },
        ),
        migrations.CreateModel(
            name="EquipmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("slug", models.SlugField(max_length=100)),
                ("short_slug", models.SlugField(max_length=10)),
                ("number", models.CharField(blank=True, max_length=10)),
                ("visible", models.BooleanField(default=True)),
                ("rentable", models.BooleanField(default=True)),
                ("count", models.IntegerField(default=1)),
                ("image", models.ImageField(blank=True, upload_to="equipment_images/")),
                (
                    "equipment_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment",
                        to="equipment.equipmentclass",
                    ),
                ),
                (
                    "equipment_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="equipment.equipmentgroup",
                    ),
                ),
                (
                    "price_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="equipment.equipmentpricegroup",
                    ),
                ),
            ],
        ),
    ]
