# Generated by Django 4.0.2 on 2022-04-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentclass',
            options={'verbose_name': 'equipment class', 'verbose_name_plural': 'equipment classes'},
        ),
        migrations.AddField(
            model_name='equipmentgroup',
            name='image',
            field=models.ImageField(blank=True, upload_to='equipment_images/'),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='equipmentitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='equipment_images/'),
        ),
    ]
